
#' Signature renormalisation
#'
#' Transform a signature into what it would look like if called from a different pipeline/genome/organism to account for the different 'mutation opportunites'
#'
#' @param signature sigverse style signature data.frames. See [sigshared::example_signature()].
#' @param opportunities_original named vector of mutation opportunities for each context. See [sig_opportunities()].
#' @param opportunities_new named vector of mutation opportunities for each context. See [sig_opportunities()].
#'
#' @returns sigverse style signature data.frame. See [sigshared::example_signature()].
#' @export
#'
#' @examples
#' opps <- sig_opportunities()
#' signature <- data.frame(
#'   channel = c("A[C>G]G", "A[C>G]C", "A[C>G]T"),
#'   type = c("C>G", "C>G", "C>G"),
#'   fraction = c(0.4, 0.1, 0.5)
#' )
#'
#' # Convert genome signature to panel signature (TSO 500)
#' sig_renormalise(
#'   signature,
#'   opps$GRCh38_genome_trinucleotide_autosomal,
#'   opps$GRCh38_tso500_trincucleotide_autosomal
#' )
sig_renormalise <- function(signature, opportunities_original, opportunities_new){

  # Assertions
  sigshared::assert_signature(signature)
  assertions::assert_numeric_vector(opportunities_original)
  assertions::assert_numeric_vector(opportunities_new)
  assertions::assert_length(opportunities_new, length = length(opportunities_new))

  # TODO: make channels_to_context conversion more clear to user to help with debug
  channels <- channels_to_context(signature[["channel"]])
  assertions::assert_names_include(opportunities_original, channels)
  assertions::assert_names_include(opportunities_new, channels)

  # Just pull the channels we need, and ensure order matches signature
  opportunities_original <- opportunities_original[channels]
  opportunities_new <- opportunities_new[channels]

  ratio = opportunities_new / opportunities_original

  # If catalogue, fix counts and recompute fraction
  if ("count" %in% colnames(signature)){
    signature[["count"]] <- signature[["count"]] * ratio
    signature[["fraction"]] <- compute_fraction_from_count(channels[["count"]])
    return(signature)
  }

  # If just a signature (no count), apply normalisation ratio.
  signature[["fraction"]] <- signature[["fraction"]] * ratio
  signature[["fraction"]] <- signature[["fraction"]] / sum(signature[["fraction"]])

  # Return
  return(signature)
}

is_infinite_or_na <- function(x){
  is.infinite(x) & is.na(x)
}


# #' Renormalise collection
# #'
# #' @param signatures A sigverse signature collection. See ([sigshared::example_signature_collection()]) for details.
# #' @param opportunities_original
# #' @param opportunities_new
# #'
# #' @returns
# #' @export
# #'
# #' @examples
# sig_renormalise_collection <- function(signatures, opportunities_original, opportunities_new){
#
# }


#' Convert counts into fractions of total counts
#'
#' Convert counts into fractions of total counts, dealing with zero sum counts by setting to zero instead of Inf
#'
#' @param counts a numeric vector of counts
#'
#' @returns a numeric vector of fractions
#' @export
#'
#' @examples
#' compute_fraction_from_count(c(10, 2, 1000, 50, 250))
#'
compute_fraction_from_count <- function(counts){
  assertions::assert_numeric(counts)
  fraction <- counts / sum(counts, na.rm = TRUE)
  fraction <- ifelse(is_infinite_or_na(fraction), yes = 0, no = fraction)
  return(fraction)
}

# take a vector of channels like  A[C>A]A, A[C>A]C, A[C>A]G and turn into 'contexts'
# like ACA ACC ACG
channels_to_context <- function(channels){
  # chars_to_drop <- c("[", ">", "]")
  channels <- sub(x=channels, pattern = ">[ACTG].*\\]", replacement = "")
  gsub(x=channels, pattern = "\\[|>|\\]\\-", replacement = "")
}

#' Autosomal context counts
#'
#' @returns list of context counts generated by [contextcounter](https://github.com/CCICB/contextcounter)
#'
#' @examples
#' sig_opportunities()
#'
#' @export
sig_opportunities <- function() {

  list(
    GRCh38_tso500_trincucleotide_autosomal = c(ACA = 44360L, ACC = 39934L, ACG = 15859L, ACT = 37266L, ATA = 24482L,
                                      ATC = 35395L, ATG = 43634L, ATT = 34160L, CCA = 60668L, CCC = 49156L,
                                      CCG = 26148L, CCT = 56173L, CTA = 21926L, CTC = 51672L, CTG = 72675L,
                                      CTT = 51143L, GCA = 49299L, GCC = 50759L, GCG = 21555L, GCT = 49806L,
                                      GTA = 27166L, GTC = 33171L, GTG = 45371L, GTT = 31980L, TCA = 50011L,
                                      TCC = 51740L, TCG = 16538L, TCT = 53400L, TTA = 25759L, TTC = 50461L,
                                      TTG = 42424L, TTT = 51723L, OTHER = 0L),
    GRCh38_genome_dinucleotide_autosomal = c(
      AC = 296799296, AT = 226707215, CC = 304463484, CG = 29403065,
      CT = 411467170, GC = 124936156, TA = 191730173, TC = 350911281,
      TG = 427309272, TT = 576938292, OTHER = 165047079
    ),
    GRCh38_genome_trinucleotide_autosomal = c(
      ACA = 119012480, ACC = 67747193, ACG = 15146753, ACT = 94892542,
      ATA = 120766156, ATC = 78713412, ATG = 107729216, ATT = 146205171,
      CCA = 107931875, CCC = 76434468, CCG = 16303633, CCT = 103793100,
      CTA = 75675881, CTC = 99106599, CTG = 118939447, CTT = 117744705,
      GCA = 84736367, GCC = 69175621, GCG = 14111520, GCT = 81848493,
      GTA = 66252975, GTC = 55279200, GTG = 88658315, GTT = 86608493,
      TCA = 115628044, TCC = 91105815, TCG = 13244081, TCT = 130932605,
      TTA = 120764978, TTC = 117811561, TTG = 111981796, TTT = 226379353,
      OTHER = 165048055
    ),
    GRCh38_genome_pentanucleotide_autosomal = c(
      AACAA = 11424148, AACAC = 6494598, AACAG = 8142211, AACAT = 9841652,
      AACCA = 6732363, AACCC = 5057050, AACCG = 658970, AACCT = 6430314,
      AACGA = 1053040, AACGC = 676410, AACGG = 902334, AACGT = 1204157,
      AACTA = 6360369, AACTC = 6482967, AACTG = 7039319, AACTT = 8108441,
      AATAA = 15759369, AATAC = 7111749, AATAG = 7169063, AATAT = 13508954,
      AATCA = 8612547, AATCC = 6428063, AATCG = 918572, AATCT = 8216106,
      AATGA = 10513404, AATGC = 6481812, AATGG = 7936885, AATGT = 9919455,
      AATTA = 11832075, AATTC = 8142634, AATTG = 7356677, AATTT = 16297551,
      ACCAA = 6264974, ACCAC = 5877403, ACCAG = 5886645, ACCAT = 6733208,
      ACCCA = 6504455, ACCCC = 4313236, ACCCG = 1119338, ACCCT = 4957778,
      ACCGA = 635932, ACCGC = 821143, ACCGG = 598230, ACCGT = 909551,
      ACCTA = 4257598, ACCTC = 6363434, ACCTG = 6705069, ACCTT = 5799039,
      ACTAA = 6159123, ACTAC = 3877157, ACTAG = 3642063, ACTAT = 5618933,
      ACTCA = 6677084, ACTCC = 6109529, ACTCG = 918549, ACTCT = 7024844,
      ACTGA = 6838274, ACTGC = 6432679, ACTGG = 5759415, ACTGT = 6808587,
      ACTTA = 5934690, ACTTC = 6245879, ACTTG = 6273839, ACTTT = 10571719,
      AGCAA = 8326982, AGCAC = 5529821, AGCAG = 7973851, AGCAT = 6744219,
      AGCCA = 8491605, AGCCC = 4945523, AGCCG = 1387748, AGCCT = 8584340,
      AGCGA = 1187087, AGCGC = 835659, AGCGG = 901494, AGCGT = 842055,
      AGCTA = 5798164, AGCTC = 5509916, AGCTG = 8271268, AGCTT = 6518582,
      AGTAA = 6924715, AGTAC = 3287053, AGTAG = 5921737, AGTAT = 5876488,
      AGTCA = 6115254, AGTCC = 4282549, AGTCG = 565359, AGTCT = 6533003,
      AGTGA = 8552514, AGTGC = 5460888, AGTGG = 7043350, AGTGT = 6338349,
      AGTTA = 5858983, AGTTC = 5908310, AGTTG = 5488531, AGTTT = 10735264,
      ATCAA = 7243994, ATCAC = 6355852, ATCAG = 5996249, ATCAT = 7693599,
      ATCCA = 6619389, ATCCC = 5518242, ATCCG = 716900, ATCCT = 6567097,
      ATCGA = 743218, ATCGC = 933946, ATCGG = 503168, ATCGT = 846571,
      ATCTA = 5809973, ATCTC = 7466279, ATCTG = 7139206, ATCTT = 8559408,
      ATTAA = 10540193, ATTAC = 6307625, ATTAG = 6360001, ATTAT = 11155933,
      ATTCA = 9458163, ATTCC = 6711951, ATTCG = 791798, ATTCT = 11113509,
      ATTGA = 6851716, ATTGC = 5372083, ATTGG = 4910795, ATTGT = 7587818,
      ATTTA = 13447822, ATTTC = 11368094, ATTTG = 10640723, ATTTT = 23586481,
      CACAA = 7658574, CACAC = 8565905, CACAG = 8847533, CACAT = 8370036,
      CACCA = 8191881, CACCC = 5483771, CACCG = 1289179, CACCT = 7249334,
      CACGA = 1122486, CACGC = 1670126, CACGG = 1291228, CACGT = 1522886,
      CACTA = 4296856, CACTC = 6030271, CACTG = 8804392, CACTT = 8263578,
      CATAA = 7021122, CATAC = 4029230, CATAG = 4922518, CATAT = 7910690,
      CATCA = 7176357, CATCC = 5213520, CATCG = 777253, CATCT = 8110034,
      CATGA = 7162381, CATGC = 5738571, CATGG = 6953175, CATGT = 7862591,
      CATTA = 6843811, CATTC = 7658020, CATTG = 6221408, CATTT = 14128323,
      CCCAA = 6988763, CCCAC = 6171722, CCCAG = 11140994, CCCAT = 5955485,
      CCCCA = 7188304, CCCCC = 3953913, CCCCG = 1548580, CCCCT = 5222488,
      CCCGA = 1071434, CCCGC = 1446401, CCCGG = 1961027, CCCGT = 1215404,
      CCCTA = 3590518, CCCTC = 5854280, CCCTG = 7052084, CCCTT = 6072835,
      CCTAA = 4880648, CCTAC = 3271851, CCTAG = 4108879, CCTAT = 4356563,
      CCTCA = 8544761, CCTCC = 9752216, CCTCG = 1467954, CCTCT = 8031106,
      CCTGA = 7607646, CCTGC = 6887270, CCTGG = 9898587, CCTGT = 7818010,
      CCTTA = 4586091, CCTTC = 7068833, CCTTG = 6172604, CCTTT = 9339847,
      CGCAA = 685383, CGCAC = 866723, CGCAG = 1117421, CGCAT = 713533,
      CGCCA = 1399813, CGCCC = 1635358, CGCCG = 414252, CGCCT = 2032392,
      CGCGA = 235999, CGCGC = 545201, CGCGG = 482407, CGCGT = 216689,
      CGCTA = 478739, CGCTC = 1002597, CGCTG = 1152493, CGCTT = 1132462,
      CGTAA = 725993, CGTAC = 406450, CGTAG = 614550, CGTAT = 846107,
      CGTCA = 786007, CGTCC = 761819, CGTCG = 159303, CGTCT = 1403791,
      CGTGA = 1606537, CGTGC = 1126931, CGTGG = 1581953, CGTGT = 1291312,
      CGTTA = 660838, CGTTC = 800869, CGTTG = 882258, CGTTT = 1491970,
      CTCAA = 8153277, CTCAC = 7218616, CTCAG = 9764689, CTCAT = 7269962,
      CTCCA = 8738610, CTCCC = 8666022, CTCCG = 1390660, CTCCT = 9846706,
      CTCGA = 1066889, CTCGC = 938726, CTCGG = 1746188, CTCGT = 982629,
      CTCTA = 6108268, CTCTC = 7850896, CTCTG = 10122565, CTCTT = 9241639,
      CTTAA = 6818809, CTTAC = 3978419, CTTAG = 4538243, CTTAT = 6179877,
      CTTCA = 8318712, CTTCC = 8358213, CTTCG = 922437, CTTCT = 10222503,
      CTTGA = 7264065, CTTGC = 5164261, CTTGG = 6675759, CTTGT = 6148991,
      CTTTA = 8485626, CTTTC = 9529406, CTTTG = 9909675, CTTTT = 15229489,
      GACAA = 5602482, GACAC = 4204072, GACAG = 6658617, GACAT = 5413460,
      GACCA = 4663226, GACCC = 3168310, GACCG = 534166, GACCT = 4427650,
      GACGA = 646084, GACGC = 572626, GACGG = 1125487, GACGT = 766723,
      GACTA = 3462083, GACTC = 3951798, GACTG = 4652705, GACTT = 5429583,
      GATAA = 5944980, GATAC = 3169958, GATAG = 3739393, GATAT = 5965473,
      GATCA = 5168914, GATCC = 3405694, GATCG = 804884, GATCT = 5061353,
      GATGA = 6141448, GATGC = 3659957, GATGG = 6192147, GATGT = 5283615,
      GATTA = 6000937, GATTC = 4994827, GATTG = 4370402, GATTT = 8809119,
      GCCAA = 5613597, GCCAC = 5769295, GCCAG = 6704078, GCCAT = 5264063,
      GCCCA = 6105682, GCCCC = 3957468, GCCCG = 1419947, GCCCT = 4599979,
      GCCGA = 1187514, GCCGC = 923088, GCCGG = 1330113, GCCGT = 708188,
      GCCTA = 3363954, GCCTC = 8080055, GCCTG = 8608830, GCCTT = 5539614,
      GCTAA = 4795993, GCTAC = 3369135, GCTAG = 3067904, GCTAT = 4103136,
      GCTCA = 6649215, GCTCC = 4419171, GCTCG = 686284, GCTCT = 5992893,
      GCTGA = 6945045, GCTGC = 5299650, GCTGG = 9207574, GCTGT = 5684812,
      GCTTA = 3876718, GCTTC = 5338687, GCTTG = 4816576, GCTTT = 7595458,
      GGCAA = 5537451, GGCAC = 4350682, GGCAG = 7814719, GGCAT = 5416845,
      GGCCA = 6273056, GGCCC = 3670848, GGCCG = 1463326, GGCCT = 5757489,
      GGCGA = 909030, GGCGC = 1322080, GGCGG = 1874933, GGCGT = 1375772,
      GGCTA = 3822413, GGCTC = 5457534, GGCTG = 8864424, GGCTT = 5264845,
      GGTAA = 4121560, GGTAC = 2383146, GGTAG = 3453963, GGTAT = 3902159,
      GGTCA = 4537666, GGTCC = 2759635, GGTCG = 519278, GGTCT = 4976769,
      GGTGA = 6021546, GGTGC = 3824175, GGTGG = 7551797, GGTGT = 4816648,
      GGTTA = 3403561, GGTTC = 3947241, GGTTG = 4329019, GGTTT = 7198873,
      GTCAA = 4335161, GTCAC = 4031843, GTCAG = 5123896, GTCAT = 4791037,
      GTCCA = 4061807, GTCCC = 3856000, GTCCG = 514344, GTCCT = 4541549,
      GTCGA = 429369, GTCGC = 545431, GTCGG = 545704, GTCGT = 501942,
      GTCTA = 3579157, GTCTC = 6648045, GTCTG = 5169524, GTCTT = 6604265,
      GTTAA = 5329631, GTTAC = 3143050, GTTAG = 3491779, GTTAT = 5053279,
      GTTCA = 6222455, GTTCC = 4084454, GTTCG = 653870, GTTCT = 6378360,
      GTTGA = 4997945, GTTGC = 3990614, GTTGG = 4744776, GTTGT = 4896114,
      GTTTA = 6411653, GTTTC = 7726637, GTTTG = 6973720, GTTTT = 12509975,
      TACAA = 8119069, TACAC = 4436780, TACAG = 7424748, TACAT = 7808331,
      TACCA = 5174763, TACCC = 3185686, TACCG = 482538, TACCT = 5017839,
      TACGA = 621779, TACGC = 435810, TACGG = 567454, TACGT = 968056,
      TACTA = 5177978, TACTC = 4264966, TACTG = 5342541, TACTT = 7224515,
      TATAA = 10225862, TATAC = 5320433, TATAG = 5375579, TATAT = 13591490,
      TATCA = 6331873, TATCC = 4374357, TATCG = 526202, TATCT = 7587374,
      TATGA = 6613814, TATGC = 4131636, TATGG = 4770277, TATGT = 8367821,
      TATTA = 9686926, TATTC = 7280126, TATTG = 6773933, TATTT = 19808130,
      TCCAA = 7265512, TCCAC = 5959481, TCCAG = 8436676, TCCAT = 7899724,
      TCCCA = 10458521, TCCCC = 5688665, TCCCG = 1606403, TCCCT = 7789472,
      TCCGA = 633015, TCCGC = 1030990, TCCGG = 778175, TCCGT = 1053364,
      TCCTA = 5405872, TCCTC = 7498263, TCCTG = 9845537, TCCTT = 9755891,
      TCTAA = 6810254, TCTAC = 5209411, TCTAG = 5276757, TCTAT = 7127918,
      TCTCA = 10535491, TCTCC = 8361098, TCTCG = 1661653, TCTCT = 12274533,
      TCTGA = 8292400, TCTGC = 7394727, TCTGG = 7302823, TCTGT = 10761699,
      TCTTA = 7117849, TCTTC = 9168466, TCTTG = 7990057, TCTTT = 15647180,
      TGCAA = 7790767, TGCAC = 5622068, TGCAG = 9108320, TGCAT = 7137363,
      TGCCA = 7186559, TGCCC = 5831352, TGCCG = 883575, TGCCT = 9218224,
      TGCGA = 696154, TGCGC = 803662, TGCGG = 962788, TGCGT = 920455,
      TGCTA = 5236853, TGCTC = 5777529, TGCTG = 8848875, TGCTT = 8711542,
      TGTAA = 8871465, TGTAC = 4173541, TGTAG = 5737300, TGTAT = 9006622,
      TGTCA = 6842998, TGTCC = 5169699, TGTCG = 778507, TGTCT = 9087433,
      TGTGA = 8628908, TGTGC = 5957312, TGTGG = 7600800, TGTGT = 11255038,
      TGTTA = 7094362, TGTTC = 6682733, TGTTG = 7929638, TGTTT = 14195875,
      TTCAA = 10971449, TTCAC = 7203190, TTCAG = 8798514, TTCAT = 10676449,
      TTCCA = 10141596, TTCCC = 7502788, TTCCG = 873633, TTCCT = 11550216,
      TTCGA = 1004984, TTCGC = 610169, TTCGG = 732838, TTCGT = 1112251,
      TTCTA = 8926938, TTCTC = 10867552, TTCTG = 11320257, TTCTT = 15518251,
      TTTAA = 15835082, TTTAC = 7214641, TTTAG = 8256001, TTTAT = 16562239,
      TTTCA = 13650276, TTTCC = 10913609, TTTCG = 1092144, TTTCT = 18918626,
      TTTGA = 11590147, TTTGC = 7813631, TTTGG = 9801528, TTTGT = 14171345,
      TTTTA = 19522861, TTTTC = 15950497, TTTTG = 15852534, TTTTT = 39233648,
      OTHER = 165049993
    )
  )
}

two_column_dataframe_to_named_vector <- function(df){
  counts <- df[[2]]
  names(counts) <- toupper(df[[1]])
  return(counts)
}
